---
name: Container

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  container:
    runs-on: ubuntu-latest
    name: Container

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: quay.io/muhlba91/fh-burgenland-bswe-3b-docusaurus:${{ github.sha }}
          push: true
